In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from stt.profitability import Profitability

In [3]:
profit = Profitability().merge_table()

In [21]:
optim_df = Profitability().optim_df()

In [ ]:
to_cut = Profitability().optim_df()[1]

In [22]:
optim_df

,index,seller_id,n_orders,rev_seller,rev_orders,cost_reviews,profit,cum_orders,cum_rev_seller,cum_rev_orders,cum_cost_reviews,cum_rev,cum_it_cost,cum_profit
375,2709,1588ac4010787100dddef64568f0ae35,3,80.0,60.00,140,-0.00,3,80.0,60.00,-140,-0.00,-3669.57,-3669.57
376,1167,19484c79cef6c062cb177aa4ef2fcc3c,1,80.0,20.19,100,0.19,4,160.0,80.19,-240,0.19,-4237.25,-4237.06
377,1844,01fd077212124329bac32490e8ef80d9,31,320.0,120.80,440,0.80,35,480.0,200.99,-680,0.99,-12533.95,-12532.96
378,1487,f593898ec748b7a8cb81fc04edafd98a,20,400.0,281.30,680,1.30,55,880.0,482.29,-1360,2.29,-15712.14,-15709.85
379,1972,a4b8d97cd5d3674eeff96abc99d8ed67,1,80.0,21.41,100,1.41,56,960.0,503.70,-1460,3.70,-15854.34,-15850.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2965,2153,edb1ef5e36e0c8cd84eb3c9b003e486d,166,880.0,7928.46,1470,7338.46,53897,1272320.0,915263.18,-776360,1411223.03,-491854.22,919368.81
2966,2833,46dc3b2cc0980fb8ec44634e21d2718e,521,1840.0,12811.12,7080,7571.12,54418,1274160.0,928074.30,-783440,1418794.15,-494225.77,924568.38
2967,534,fa1c13f2614d7b5c4749cbc52fecda94,585,1600.0,19404.20,6200,14804.20,55003,1275760.0,947478.50,-789640,1433598.35,-496875.17,936723.18
2968,67,7e93a43ef30c4f03f38b393420bc753a,336,1680.0,17643.19,3360,15963.19,55339,1277440.0,965121.69,-793000,1449561.54,-498390.50,951171.04
2969,868,53243585a1d6dc2643021fd1853d8905,358,960.0,22277.60,5450,17787.60,55697,1278400.0,987399.29,-798450,1467349.14,-500000.00,967349.14